server.port=8086

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8081/eureka

logging.pattern.console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

spring.cloud.gateway.discovery.locater.enabled=true
spring.cloud.gateway.discovery.locater.lower-case-service-id=true

