server:
  port: 8082

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
