spring:
  application:
    name: ticket-service
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:postgresql://localhost:5432/tickets_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticket-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
